version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/nestdb
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  mongo-data:
